### ISSUE TITLE
Incompatbility between BetterBuildersWands and ColossalChests

### ISSUE THREAD

**Issue by KidsDontPlay** [CyclopsMC/ColossalChests#100]
Hi,
When I try to extend the iron chest wall with the wand it places copper chest walls instead.

ColossalChests-1.12.2-1.6.8
CyclopsCore-1.12.2-0.11.1
BetterBuildersWands-1.12-0.11.1.245+69d0d70
Forge 14.23.1.2590

https://github.com/portablejim/BetterBuildersWands/issues/64

**Comment by rubensworks** [comment]
Haven't used that mod myself, but I'm pretty sure the mod has a config for blocking that behaviour. (FYI, all walls are the same block/item, just with different metadata)

In any case, not an issue with CC.
