### ISSUE TITLE
[1.12.2] GUI display error/crash while extracting items with a hopper

### ISSUE THREAD

**Issue by lavraleksej** [CyclopsMC/ColossalChests#101]
#### Issue type:
- :bug: Bug

____
#### Short description:
Colossal Chest fails to display its contents while items are being pulled out of it into a Multi-Storage EnderLink chest with a hopper, second EnderLink chest is placed in a different dimension
The chest is a 4x4 Wooden chest, with two interfaces
Items are intact and continue being transferred, reloading fixes the display issue

#### Expected behaviour:
Items are displayed correctly

#### Actual behaviour:
The chest appears empty except for the stack currently being pulled, and the following:
https://pastebin.com/ntb60L2C
gets printed to console. Attempting to put items in the chest (via picking up and clicking on a slot) in this state crashes the game:
https://pastebin.com/2dkqhYVr
#### Steps to reproduce the problem:
1. Build a Collossal Chest with an interface in the bottom layer, put several stacks of items in it
2. Put a Hopper under the interface, pointing into an Ender-Link chest
3. Place a second EnderLink chest in another dimension
4. Open the first EnderLink chest, then open the Collossal Chest
____
#### Versions:
- This mod: ColossalChests-1.12.2-1.6.8
- CyclopsCore: CyclopsCore-1.12.2-0.11.4
- Minecraft: 1.12.2
- Forge: 14.23.2.2615
- Multi-Storage: multistorage-1.12.0-1.4.7

**Comment by jamzam90** [comment]
I have also experienced this issue. However it is not plugged into any other systems including hoppers.
