### ISSUE TITLE
:heavy_plus_sign: set direction of chest

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/ColossalChests#103]
I can't see a way to determine the direction of the collossal chest. 

By placing the core or by facing in a specific direction while completing the chest, I tried to make it open in a desired direction, but the lid opens in a seemingly random direction.

Versions:

- This mod: ColossalChests-1.10.2-1.6.0.jar
- CyclopsCore: CyclopsCore-1.9.4-0.10.4.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2185.jar

**Comment by rubensworks** [comment]
Sorry, 1.10 is not maintained anymore. this is possible in 1.12

**Comment by rubensworks** [comment]
Also, this should actually be possible in 1.10 already based on the core position.

**Comment by 7eggert** [comment]
I didn't find any change in the documentation so I still would not know how to chose a direction.

**Comment by rubensworks** [comment]
The position of the core indicates the direction of the chest.

**Comment by 7eggert** [comment]
It should, but the chest opened north with the core in the NW corner and south with the core in the NE corner, while a 2⋅2 chest with the core in the NE corner opened west. (AFAIR; it's burried)

Placing the core while facing N/S/W/E did not change the direction.

**Comment by rubensworks** [comment]
Yeah, that was a bug in the 1.10 version, it's fixed in 1.12, won't be backported.
