### ISSUE TITLE
Wrong blockplacing with unbreakable wand

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/ColossalChests#104]
#### Issue type:

- :bug: Bug

____
#### Short description:

https://files.pudding.tk/tuz8wc8by4.mp4 see video <.<

#### Expected behaviour:

that exactly the blocks are created, which should actually be used.

#### Actual behaviour:

I tried with an unbreakable wall to place the colossal chests. However, not the blocks were used that you actually need. although the right blocks (in this case the obsidian wall) are pulled out of the inventory and used up, they turn into a smaller wall.

apparently works only with the unbreakable wall of better builders wall mod

#### Steps to reproduce the problem:

1. Craft any walls higher then wood
2. Place 1-2 pr more with ur hand.
3. Use the unbreakble Wand
4. U see, wrong walls (or nothing needs a blockupdate)

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: ColossalChests-1.12.2-1.6.9
- CyclopsCore: CyclopsCore-1.12.2-0.11.4
- Better Builders Wand - BetterBuildersWands-1.12-0.11.1.245+69d0d70
- Minecraft: 1.12.2
- Forge: 14.23.2.2619
- Modpack: Moderskyblock 3 v3.1.5.3

**Comment by rubensworks** [comment]
Please report this to the wands mod, this is not a Colossal Chests issue.

Feel free to reference the issue here, I might be able to help.

**Comment by ghost** [comment]
i think the mod maker doesnt work anymore on this mod... last update jun 2017

**Comment by rubensworks** [comment]
Nothing I can do about it on my end, sorry.
