### ISSUE TITLE
Breaking Interface Bug

### ISSUE THREAD

**Issue by thelapisfox** [CyclopsMC/ColossalChests#107]
#### Issue type: Bug

____
#### Short description:
Breaking an interface drops all items and deletes some. Mod Pack: Modern Skyblock 3: Departed

#### Expected behaviour:
Chest should remain as is, with inventory still stored within the Core. Items should not spill out nor be deleted.

#### Actual behaviour:
Upon breaking an interface in order to resize the chest, all items spill out. Upon restoring the chest and replacing everything back into the chest, 50% of items are found to be missing. Was trying to upgrade from a 3x3 to a 4x4 as it was full. Half of items gone. Lucky to have 30 minute increment back-ups or would have lost days of work.

#### Steps to reproduce the problem:

1. Build a 3x3 chest with an interface on chest (mine was bottom middle on side, not sure if that will make a difference).
2. Fill chest.
3. Break said interface.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.6.10
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2652

**Comment by rubensworks** [comment]
Must be a recent regression, as this was definitely not the case in the past. Thanks for reporting.
