### ISSUE TITLE
Game Crash when placing core in ATM3

### ISSUE THREAD

**Issue by Pontiac76** [CyclopsMC/ColossalChests#109]
#### Issue type:

- :bug: Bug

____

#### Short description:

Game crashes hard when placing at least the wooden core (Playing in survival).  Playing local in single player.

#### Steps to reproduce the problem:

1. Place down 7 of the 8 required block to make a 2x2 chest
2. Place down the core, watch the core not be placed, game proceeds to crash
3. Reload and wait another 5 minutes.
4. After starting up, see that the chest is invisible.

#### Expected behavior:

Chest forms, can access, client doesn't crash.

____

#### Versions:

- This mod: 1.12.2-1.6.11 and 1.12.2-1.6.10
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Log file:

https://pastebin.com/raw/w1ZzwZTp

**Comment by Pontiac76** [comment]
AFTER the fact of posting this, something new just showed up.

If I break one of the walls off the 2x2, then put the wall back, the chest forms, and I have access to it.

So for experimentation, I placed JUST the core, no other walls, and the game dies on 1.6.10.  (Downgraded to see if that was the problem)

**Comment by rubensworks** [comment]
Seems like a major bug, strange that this hasn't been reported before, will look into this soon.

**Comment by Pontiac76** [comment]
Just for more follow up, 

I found that this isn't related to just the wooden chest, but, also had the crash when placing the copper core while in ATM3.

I also went and created an instance that just had Colossal Chests and JEI and I could create chests, and place the cores solo and no crash happened.  This seems to be some kind of conflict in ATM3.

**Comment by rubensworks** [comment]
In that case, could you report this to the authors of ATM3 as well? (Be sure to link back to this issue)

**Comment by Pontiac76** [comment]
I did last night.  I was on Discord in both the ATM3 chat channel as well as in your ColossalChests channel and linked to here.  Not sure of what other methods to notify them with yet.  (At work now, can't check)

**Comment by rubensworks** [comment]
This would be the place I guess: https://github.com/AllTheMods/ATM-3/issues

<blockquote><img src="https://avatars0.githubusercontent.com/u/26031972?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/AllTheMods/ATM-3">AllTheMods/ATM-3</a></strong></div><div>ATM-3 - Official ATM3 Repo</div></blockquote>

**Comment by Pontiac76** [comment]
Thanks.

**Comment by Pontiac76** [comment]
After having Twitch use the most recent version of Java, I'm able to place stuff now.  Closing this guy.

Thanks.

**Comment by rubensworks** [comment]
Ah, that's good news. An `Unexpected error` is indeed typically caused by Java itself.
