### ISSUE TITLE
Uncolossal chest + refined storage = permanent crash

### ISSUE THREAD

**Issue by AkashaP** [CyclopsMC/ColossalChests#110]
#### Issue type:

- :bug: Bug

____

#### Short description:

Connecting a refined storage external bus pointing to an uncolossal chest with an active refined storage system causes a crash (Ticking block entity)

The game crashes when the world is loaded back up, making it impossible to play anymore.

#### Steps to reproduce the problem:

1. Create a simple refined storage system with a controller and grid (maybe 1 crafter with 1 recipe in it)
2. Place uncolossal chest
3. Place external storage bus pointing to uncolossal chest going to the refined storage system

#### Expected behaviour:

not crash? it works fine with regular colossal chests so
____

#### Versions:

(bundled in Sky factory 3 version 3.0.15)

- This mod: 2.2.0.52
- Minecraft: 1.10.2
- Refined storage 1.2.26
- Forge: 12.18.3.2477

#### Log file:

[https://pastebin.com/VdF20Xch](url)

**Comment by rubensworks** [comment]
Yeah, that's a problem on RS's end, they assume that the uncolossal chest is a colossal chest as well, which is not the case.

I would suggest to report it to their repo, but I think they don't support 1.10 anymore.
