### ISSUE TITLE
Odd Lag in Sky Factory 3

### ISSUE THREAD

**Issue by xylonh** [CyclopsMC/ColossalChests#113]
#### Issue type:

- :bug: Bug

Odd Lag in Sky Factory 3 Started when I started using the chest, has not happened on previous map.

#### Short description:

After I began using the chest, i noticed lag immediately even with very few items (<1000). I kept playing til end game but the lag keeps getting worse, taking more than a second to simply interact with any items in the chest not to mention crafting with it. This has not happened in previous usages of colossal chests, in fact i can load a different save that has 6 times the items in it and the chest is very responsive. 

#### Steps to reproduce the problem:

I'll include two save files named Save 1 and Save 2
1. Interact with the chest in Save 1 compared to Save 2, try to pick up a stack of items or craft something. There is exponentially more lag in 1 even though it's only storing ~20% the amount of items. 

[Save 1.zip](https://github.com/CyclopsMC/ColossalChests/files/2407639/Save.1.zip)

[Save 2.zip](https://drive.google.com/open?id=1apae_rRhOofZg8fdfnWLYLIbJGYvjxF_)
#### Expected behaviour:

The two save files show that some bug is happening with the chest in save 1. i'm unable to find out what the problem is. 

#### Versions:

- This mod: 1.6.0
- Minecraft: 1.10.2
- Forge: 12.18.3.2477
- Sky Factory: 3.0.15

**Comment by rubensworks** [comment]
> or craft something

What do you mean by this? This mod does not allow you to do any crafting directly. Are you using any other mod for this? Because that mod may be the one that is producing the lag.

**Comment by xylonh** [comment]
You're absolutely right, I'm using refined storage to access the chest, completely forgot that was a separate mod. My bad.
