### ISSUE TITLE
9x9 buried chest won't stay open [1.12.2, Stoneblock 1.0.10 Beta]

### ISSUE THREAD

**Issue by grannymc** [CyclopsMC/ColossalChests#115]
#### Issue type:

- :bug: Bug

____

#### Short description:

I built a 9x9x9 chest buried 8 deep in stone with a 9x9x9 open ceiling above. The chest would not stay open unless I dug down one level in front of it and stood on that level.

#### Steps to reproduce the problem:

1. See descrfiption.

#### Expected behaviour:

Stay open until ESC key selected.

#### Versions:

- This mod: 1.12.2-1.16.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by grannymc** [comment]
Correction: Stoneblock 1.0.19 Beta

**Comment by rubensworks** [comment]
What do you mean exactly with _would not stay open_?

Does it visually close?
Or can you not open the GUI?
