### ISSUE TITLE
Interaction with tinker's crafting station and colossal chest can delete your inventory

### ISSUE THREAD

**Issue by FallenEagle1** [CyclopsMC/ColossalChests#116]
#### Issue type:

- :bug: Bug

____

#### Short description:

Interesting interaction between tinkers construct and colossal chests. Not sure which side the issue is on, but was leaning towards this mod, partly because of other interactions as well, will get to those. This was tested with just colossal chests and tinkers to start with, then with AE2 and refined storage afterwards.

When a chest is set up, a tinkers construct crafting table can be put onto the side of the core or an interface and have access to the items within. If you have a table on one of these (interaction happens with both) and you break part of the colossal chest, the next time you open the crafting station, no items will appear for you to pull out of the chest through the crafting station and your inventory will be erased.

The reason I'm thinking this may be more related to this mod instead of tinkers is because of the following. I the set up an AE2 and a RS system on the chest to see what happens. AE2 used a storage bus, while RS used an external storage to access the chest. Then just had a terminal to see/access the items within the chest. Broke the side of the chest like before and then accessed the terminals. The players inventory still exists, but in the terminals you can still see every single item that was in the chest. You cannot interact with them in any was, but you can still see what was in it.

#### Steps to reproduce the problem:

1. Set up a colossal chest. I used an obsidian one when initial testing, but they all exhibit this.
2. Place a tinkers crafting station against a chest core or chest interface.
3. Break on of the sides of the chest so it is no longer formed.
4.  Access the tinkers station.

#### Expected behaviour:

* Tinker's crafting table not being able to read anything from the chest, and not delete a players inventory.
* AE2 and refined storage not being able to read anything from the chest.

____

#### Versions:

- Colossal Chests: 0.11.10
- Minecraft: 1.12.2
- Forge: 2770
- Tinker's Construct: 2.11.0.106

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
The deletion part had apparently already been fixed in-dev. The incorrect exposure of slots for an incomplete chest has been fixed now as well.

I won't release this fix just yet, as a lot of changes in the background are being worked on, which will be released in a couple of weeks.
