### ISSUE TITLE
Colossal Chests crashes when placing down wall blocks

### ISSUE THREAD

**Issue by ESTD3** [CyclopsMC/ColossalChests#122]
#### Issue type:

- :bug: Bug/Crash

____

#### Short description:

Was placing down colossal chests wooden wall blocks when it crashed the server. Was playing with my friend.

#### Steps to reproduce the problem:

1. Use latest Colossal Chests/Cyclops core
2. Start making 5x5 colossal chests
3.???
4. Profit - it crashes
1. ...

#### Expected behaviour:

Not to crash.
____

#### Versions:

- This mod: ColossalChests-1.14.4-1.7.4 and CyclopsCore-1.14.4-1.5.5
- Minecraft: 1.14.4
- Forge: 28.1.61

#### Log file:

Crash report: https://pastebin.com/Empj0sJd

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
