### ISSUE TITLE
[1.14.4] [1.7.4] Missing Textures to diamond chest

### ISSUE THREAD

**Issue by raziel23x** [CyclopsMC/ColossalChests#123]
#### Issue type:

- :bug: Bug

____

#### Short description:

Made a Diamond Version of the chest and the textures are missing

![image](https://user-images.githubusercontent.com/441966/67828987-d2882480-faab-11e9-8d46-4b9a79e709a1.png)

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

the graphics to actually show

____

#### Versions:

- This mod: 1.7.4
- Minecraft: 1.14.4
- Forge: 28.1.74

**Comment by rubensworks** [comment]
Do you also have Iron Chests installed by any chance?

**Comment by raziel23x** [comment]
yes i do i have both iron chest and iron shulker boxes installed
