### ISSUE TITLE
1.14.4-1.7.4 Server crashes when someone tries to upgrade or pick up a chest

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/ColossalChests#124]
#### Issue type:

- :bug: Bug

____

#### Short description:

The mod crashes a dedicated server when a player tries to pick up a piece of the chest wall already put down, and also when they try to upgrade a complete chest.

#### Steps to reproduce the problem:

1. install [World of Dragons - A New Age ](https://www.curseforge.com/minecraft/modpacks/world-of-dragons-a-new-age)
1. join the server given
1. place down parts of the chest
1. get on top of a chest wall part and hold shift and left click to pick it up (I have carryon in the pack)
1. crash the server

- **Optionally**-

1. install [World of Dragons - A New Age ](https://www.curseforge.com/minecraft/modpacks/world-of-dragons-a-new-age)
1. join the server given
1. full build a chest
1. create a chest upgrade and try to apply it
1. crash the server

#### Expected behaviour:

not crash when picking up part of the chest, just that it reinvalidates
not crash when they try to upgrade it
____

#### Versions:

- This mod: 1.7.4
- Minecraft: 1.14.4
- Forge: 28.1.80

#### Log file:

report | paste
--- | ---
crash-2019-11-04_13.22.00-server.txt | http://paste.ubuntu.com/p/qc4w7r2KSS/
crash-2019-11-04_13.25.19-server.txt | http://paste.ubuntu.com/p/Cthcnhch57/
crash-2019-11-04_13.46.39-server.txt | http://paste.ubuntu.com/p/725twG2n58/

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by kreezxil** [comment]
thanks for responding. :)
