### ISSUE TITLE
Giant Chests Render Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [CyclopsMC/ColossalChests#126]
#### Issue type:

- :bug: Bug

____

#### Short description:

The chest blocks renders incorrectly when placed underwater. It displays water flowing down it's sides.

#### Steps to reproduce the problem:

1. Create a chest underwater.
2. Observe water flowing down it's sides.

#### Expected behaviour:

It should instead render similarly to how a chest appears underwater.

____

#### Versions:

- `Minecraft v1.14.4`
- `Forge v28.1.90`
- `Colossal Chests v1.7.5`

**Comment by rubensworks** [comment]
I have to wait for a Forge addition before this can be fixed: https://github.com/MinecraftForge/MinecraftForge/issues/6319

**Comment by WenXin20** [comment]
Bluepower had a workaround, it's glass had a similar issue that I reported at Qmunity/BluePower#498, if that helps any.

**Comment by rubensworks** [comment]
Apparently Forge has a fix in 1.15, but not forge 1.14 (LTS), which is kind of awkward: https://github.com/MinecraftForge/MinecraftForge/commit/f93289e01c7a5a36aa8105c5ade2eb8402a6a49c

Something to keep in mind for the 1.15 port.
