### ISSUE TITLE
Crash when upgrading chest

### ISSUE THREAD

**Issue by Anuuviem** [CyclopsMC/ColossalChests#127]
note, this is on a server with several other mods. the only mod reference I saw was with quark and cyclops

#### Issue type:

- Crash when upgrading chest

____

#### Short description:

When attempting to use upgrade on 2x2 chest, immediately crashes server

#### Steps to reproduce the problem:

1. build 2x2 wooden chest
2. put some inventory
3.clear space to ensure smooth upgrade to 3x3
4.forget to have parts in inventory to upgrade
5.put upgrade in hand
6.right click on pre-existing chest
7.profit

#### Expected behaviour:

upgrade to next size chest or txt readout saying i dont have parts/dont have room/ or clear inventory

____

#### Versions:

- This mod: 1.7.5
- Minecraft: 1.14.4
- Forge: 28.1.90

#### Log file:

https://pastebin.com/fywe5Qm1

**Comment by rubensworks** [comment]
Hmm, looks like my fix in 874a81fd79a59413286f353f78529c323f8bad50 was incomplete...
