### ISSUE TITLE
Lighting issues when relogging in servers

### ISSUE THREAD

**Issue by Gerdathlete** [CyclopsMC/ColossalChests#128]
#### Issue type:

- :bug: Bug

____

#### Short description:

When most of a chest is covered (in my case only 6 blocks on the top face of a 3x3 are exposed) and you relog, the chest appears dark until it receives a block update.

#### Steps to reproduce the problem:

1. Make a 3x3 chest
2. Surround the chest in stone, leaving a few open spots at the top of the chest
3. Relog
4. Chest is now dark
5. Place something on the chest - Chest looks normal

#### Expected behaviour:

The chest should not become dark after a relog.

____

#### Versions:

- This mod: 1.12.2 - 1.7.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
This may be a vanilla thing, will look into it.

**Comment by rubensworks** [comment]
I can't reproduce this problem myself.
Could you try this out yourself without any other mods installed?
