### ISSUE TITLE
items dissapear when breaking chest

### ISSUE THREAD

**Issue by Redd56** [CyclopsMC/ColossalChests#129]
1.14.4 branch effecting bug (may effect other branches)

Bug

1: throw items into the chest
2: now break one of the blocks and place it back
3: all your items are gone!

#### Expected behaviour:
items not to dissapear on chest breaking but either drop or get stored in teh blocks themslves

#### Versions:

- This mod: 1.7.6
- Minecraft: 1.14.4 server
- Forge: 28.1.106

**Comment by rubensworks** [comment]
Can you reproduce this without any other mods installed? Because last time I tried this, this worked just fine.

**Comment by Redd56** [comment]
okay update to the issue: it seems to only be when you break the core
ill test it on its own

**Comment by BottomNotch** [comment]
This just happened to me in 1.12.2 in a modpack.  I'll try to reproduce without other mods later.
