### ISSUE TITLE
Broken textures when using Iron Chests

### ISSUE THREAD

**Issue by bessiq** [CyclopsMC/ColossalChests#132]
#### Issue type: broken texture/rendering

- :bug: Bug

____

#### Short description: 
I recently built a 9x9 obsidian colossal chest. All blocks except for the core are interfaces. Unfortunately, the chest is not rendering the texture upon completion (screenshot attached). I do have Iron Chests installed. My wooden colossal chest renders properly. For what it's worth, I did build most of this chest using a Building Gadget, but placed the last few blocks (including the core) by hand. Also, this is on a server, but I can test in singleplayer also if desired.

And this is probably not related, but I was curious - the obsidian wall recipe requires a log in the middle, instead of a diamond wall. Is this intended?

#### Steps to reproduce the problem:

1. Build Obsidian Colossal Chest

#### Expected behaviour:

A beautiful, magnificently colossal chest. 
____

#### Versions:

- This mod: ColossalChests-1.15.2-1.7.7
- Minecraft: 1.15.2
- Forge: forge-31.1.74
- Iron Chests: ironchest-1.15.2-10.0.3
- Modpack: ATM5 v1.22

#### Log file:

Can provide server and/or client logs if desired. Thanks for bringing Colossal Chests to 1.15!

![2020-05-08](https://user-images.githubusercontent.com/7315505/81408008-6e08ea80-910a-11ea-9316-47634d7d585a.png)

**Comment by rubensworks** [comment]
Thanks for reporting!
