### ISSUE TITLE
Broken textures for all chests above wooden tier

### ISSUE THREAD

**Issue by Creatures-5** [CyclopsMC/ColossalChests#133]
Visual bug.
All the colossal chests other than wooden have missing texture.

#### Versions:

- ColossalChests: 1.15.2-1.7.7.jar
-IronChests: 1.15.2-10.0.3.jar

- Minecraft: 1.15.2
- Forge: 1.15.2-forge-31.1.41

**Comment by rubensworks** [comment]
This is a duplicate of #132, so I'm merging this issue there.
Thanks for reporting!
