### ISSUE TITLE
SearchBar

### ISSUE THREAD

**Issue by ZR-00** [CyclopsMC/ColossalChests#134]
#### Issue type:
theres time when you just have so much stuff, you'll eventually .... dont remember where you placed something... and that something is reside inside the mahoosive collossal chest.

what im saying is, when you placed random stuff on it, it becomes a challage to find that one thing of an item , surrounded to hell with other items that you own

- :heavy_plus_sign: Feature request
kinda need searchbar
____

**Comment by rubensworks** [comment]
I want this mod to remain relatively simple, so I purposely don't want to add a search bar. See #64
