### ISSUE TITLE
16x16 chest won't stay open

### ISSUE THREAD

**Issue by HimitsuYami** [CyclopsMC/ColossalChests#136]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I open the chest with my player character more than 8 blocks away from the core the chest opens for a split second and then closes. By closes I mean both the physical chest and the GUI.

[Video showcasing the bug](https://youtu.be/D_Dqp1d09mU)

#### Steps to reproduce the problem:

1. Build chest. (in my case I built a 16x16x16 chest)
2. Open chest while standing more than 8 blocks away from the core.

#### Expected behaviour:

Chest should stay open as long as I'm in range to interact with one of the blocks.

____

#### Versions:

- This mod: 1.7.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by HimitsuYami** [comment]
No problem. I look forward to the fix
