### ISSUE TITLE
breaking the chest's core in 1.15.2 will delete all of the items that were in the colossal chest and not drop them on the ground

### ISSUE THREAD

**Issue by SoulRacer65** [CyclopsMC/ColossalChests#137]
#### Issue type: 

- :bug: Bug

____

#### Steps to reproduce the problem: 

1. Make a Colossal Chest (2. put items in the Colossal Chest (3. break the Colossal Chest Core

#### Expected behaviour:

____Breaking the core while items are in the chest will not drop anything but the core on the ground.

#### Versions:

- This mod: 1.7.9
- Minecraft: 1.15.2
- Forge: 31.2.30

**Comment by rubensworks** [comment]
Thanks for reporting!
