### ISSUE TITLE
[1.15.2] Configs Not Being Read

### ISSUE THREAD

**Issue by TrueDakkon** [CyclopsMC/ColossalChests#138]
Version:
---------------------
- Mod: 1.7.10
- Minecraft: 1.15.2
- Forge: 31.2.31
---------------------
Bug:
---------------------
When making adjustments to the config file and then reopening the game, none of the configurations made will be applied to the mod when in game.
Example: Changing the `metalVariants` to `false` doesn't reflect when in game. Same with changing the size limitations.
Even with both of those changes made, the metal varinats can still be crafted and the chest isn't limited to the max size set by the config.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by TrueDakkon** [comment]
Diamond and obsidian variants are still being ignored even with metalVariants set to false. Can confirm that other ones are fixed.
