### ISSUE TITLE
metalVariants Not Recognizing Diamond/Obsidian Variants

### ISSUE THREAD

**Issue by TrueDakkon** [CyclopsMC/ColossalChests#139]
Diamond and obsidian variants are still being ignored even with metalVariants set to false. Can confirm that other ones are fixed.

_Originally posted by @TrueDakkon in https://github.com/CyclopsMC/ColossalChests/issues/138#issuecomment-663905741_

**Comment by rubensworks** [comment]
Strictly speaking diamond and obsidian are not metals :-)
But agreed, this is not ideal.
