### ISSUE TITLE
Duplication glitch with upgrading Colossal Chest

### ISSUE THREAD

**Issue by jayschuster** [CyclopsMC/ColossalChests#140]
#### Issue type:

🐛 

____

#### Short description:

A very simple and easy duplication glitch with Wooden Colossal Chests

#### Steps to reproduce the problem:

1. Create a wooden Colossal Chest with 1 Interface (only tested with Wood-->Copper)
2. Create a Chest Upgrade Tool
3. Obtain 2 Copper Chest Walls, 1 Copper Chest Interface, and 1 Copper Chest Core
4. Right click the upgrade tool on the Colossal Chest with the Copper parts in your inventory
5. Collect all the dropped items, and put them back in the Colossal Chest

#### Expected behaviour:

The chest should either drop all the items on the floor and upgrade, or retain its inventory and upgrade.

____

#### Versions:

- This mod: 1.7.11
- Minecraft: 1.15.2
- Forge: 31.2.31

**Comment by rubensworks** [comment]
Oh, that's not good at all...
Thanks for reporting!
