### ISSUE TITLE
Broken wall - not core - lost items

### ISSUE THREAD

**Issue by AcidaliaP** [CyclopsMC/ColossalChests#141]
Hello, if this is a duplicate feel free to delete it. I've mostly moved on so I probably won't be back, but i figured i'd drop a line. I'm playing on Roguelike Adventures and Dungeons, on a server, and breaking the chest wall led to a loss of items. Definitely left the core alone. Tried a few times with just the one item and it was consistent. 

Have a good one!

**Comment by rubensworks** [comment]
I assume you are not using the latest mod version, if not so, make sure to use the proper issue template.
