### ISSUE TITLE
it looks weird if you finish building a chest while inside of it

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/ColossalChests#142]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. Finish constructing a chest while inside of it

#### Expected behaviour: either suffocating or going inside the chest

____

#### Versions:

- This mod: 1.15.2
- Minecraft: 1.15.2
- Forge: 1.15.2

**Comment by rubensworks** [comment]
Could you share a screenshot of what you see exactly?

Suffocating is not intended behaviour in any case.
