### ISSUE TITLE
Items lost

### ISSUE THREAD

**Issue by Void-Where-Prohibited** [CyclopsMC/ColossalChests#143]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...Created Colossal chest 4x4
2. Upgraded chest to 12x12, removing and replacing core (chest was dead center of 12x12 area initially)
3. recreated chest and items no longer in core

#### Expected behaviour:

____

#### Versions:

- This mod: 1.7.3
- Minecraft: 1.12.2
- Forge: 1.12.2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> removing and replacing core (chest was dead center of 12x12 area initially)

This is the problem.
The core contains all chest items.
If you remove it, all items will be dropped in the world (unless disabled in the config).
