### ISSUE TITLE
Long time "waiting for server" on 1.16.4 with my mods

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/ColossalChests#145]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

Long time "waiting for server" on 1.16.4 with my mods

#### Steps to reproduce the problem:

0. have chestAnimation = false in the config
1. open a collossal chest
2. wait LONG
3. **Chest open animation happens**
____

#### Versions:

Minecraft 1.16.4 / forge 35.1.4

Basic-Nether-Ores-1.16.4.jar
Big-Buckets-1.16.4.jar
BowInfinityFix-1.16.4.jar
Chargers-1.16.4-3.0.2.4.jar
ChickenChunks-1.16.4-2.7.0.85-universal.jar
CodeChickenLib-1.16.4-3.5.0.401-universal.jar
ColossalChests-1.16.4-1.7.12.jar
CommonCapabilities-1.16.4-2.5.5.jar
Corpse-1.16.4.jar
CraftTweaker-1.16.4-7.1.0.79.jar
CraftingCraft-1.16.4.jar
CyclopsCore-1.16.4-1.9.4.jar
Diamond-Glass-1.16.4.jar
DoubleSlabs-1.16-3.4.10.jar
EditSign-Forge-1.16.4-2.2.0.jar
EnderBags-1.16.2-6.2.0.jar
EnderStorage-1.16.4-2.7.0.161-universal.jar
EverlastingAbilities-1.16.4-1.6.3.jar
Flopper-1.16.4-1.0.6.jar
Futurepack-1.16.4.jar
HarvestWithDispenser-B3.0.0.jar
Immersive-Portals-1.16.4.jar-
IntegratedCrafting-1.16.4-1.0.10.jar
IntegratedDynamics-1.16.4-1.1.22.jar
IntegratedREST-1.16.4-1.1.2.jar
IntegratedTerminals-1.16.4-1.1.0.jar
IntegratedTunnels-1.16.4-1.6.14.jar
Large-Fluid-Tank-1.16.4.jar
More-Charcoal-1.16.4.jar
NaturesCompass-1.16.4-1.8.6.jar
Placebo-1.16.3-4.3.3.jar
ScalableCatsForce-2.13.3-build-6-with-library.jar
Simple-Magnets-1.16.4.jar
Solar-Generation-1.16.4.jar
StructuredCrafting-1.16.4-0.2.2.jar
WorldEdit-CUI-FE3-1.16.4-3.0.8.jar
XaerosWorldMap_1.11.7_Forge_1.16.4.jar
Xaeros_Minimap_21.0.0_Forge_1.16.4.jar
appliedenergistics2-8.1.0.jar
architectury-1.2.70-forge.jar
cloth-config-forge-4.1.3.jar
cofh_core-1.16.3-1.1.6.jar
collective-1.16.4-1.53.jar
compact-crafting-1.0.0-alpha.2.jar
compactmachines-4.0.0-alpha.6.jar
fixedanvilrepaircost_1.16.4-1.1.jar
ftb-gui-library-1604.1.1.26.jar
infinitetrading_1.16.4-1.2.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.4-11.2.10.jar
ironshulkerboxes-1.16.4-5.1.11.jar
itemcollectors-1.0.9-mc1.16.4.jar
jei-1.16.4-7.6.1.65.jar
light-overlay-5.6.1.jar
mcjtylib-1.16-5.0.15.jar
mobcatcher-3.1.jar
nametagtweaks_1.16.4-1.2.jar
rftoolsbase-1.16-2.0.9.jar
rftoolsbuilder-1.16-3.0.13.jar
rftoolscontrol-1.16-4.0.6.jar
rftoolspower-1.16-3.0.8.jar
rftoolsstorage-1.16-2.0.8.jar
rftoolsutility-1.16-3.0.20.jar
spiders-2.0-1.16.4-1.0.4.jar
tesseract-1.0.17-mc1.16.4.jar
theoneprobe-1.16-3.0.7.jar
thermal_cultivation-1.16.3-1.1.6.jar
thermal_expansion-1.16.3-1.1.6.jar
thermal_foundation-1.16.3-1.1.6.jar
thermal_innovation-1.16.3-1.1.7.jar
thermal_locomotion-1.16.3-1.1.6.jar
trashcans-1.0.6-mc1.16.4.jar
worldedit-forge-mc1.16.3-7.2.1-dist.jar
#### Profiler output:

Not available for Minecraft 1.16.4?

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Not available for Minecraft 1.16.4?

Hmm, that's unfortunate.

In that case, could you show a reproducible setup without any other mods installed, so we can make sure that this mod is actually causing the problem?

**Comment by 7eggert** [comment]
I just tried only loading C' Chests and Cyclops Core; Minecraft did freeze for maybe a minute before opening the chest.

**Comment by rubensworks** [comment]
Could you show a reproducible setup?

**Comment by 7eggert** [comment]
I'm using Minecraft 1.16.4 on linux with Java 14. Using Java 15, my other mods do not run (nashorn library missing), but the chest does work fast.

**Comment by rubensworks** [comment]
That wasn't what I was asking :-)

Could you show a reproducible setup, i.e., what type chest are you building, what is inside it, how big is it, ...

**Comment by 7eggert** [comment]
Any chest works as a test. I built a 3⋅3 wood chest and opened it.

What I tested:

When I was on one PC, I could not use Java 15 (now tested: even without mods it doesn't start) so I installed Java 14 and set that as the JRE to run;

on my other PC, I copied the minecraft directory, the launcher too and I was able to run the integrated JVM (Java 15). I could run all my mods (from the same network share), and your chests worked well and fast.

When I did repeat that on my main PC by renaming my .minecraft directory and copying the minimal amount, it again demanded the missing nashorn lib. Both PCs do run the same version of opensuse tumbleweed.

…

Now I installed the latest forge (instead of recommended) on my primary desktop PC; It does run with the integrated Java and the delay still happens.

**Also it does animate opening the chest despite `chestAnimation = false`.**

I have a different mod that also does have display problems - also only on my main PC or on my other PC with Java 14. I suspect it to be related to my graphics card / kernel module: Advanced Micro Devices, Inc. R9 280X / amdgpu 
On my other system, I have some intel chipset.

---

At this point, I currently don't know how to test that. Maybe if disabling the animation would work, I could still use the chest. Shall I make a separate issue for that?

**Comment by rubensworks** [comment]
It sounds like this occurs on just one machine. Perhaps this is just an machine-specific issue and not a mod issue?

**Comment by 7eggert** [comment]
I suspect it might be a different graphics function being called depending on the java version and hardware acceleration capabilities.

If you could fix the chestAnimation = false, I could test that.

Edit: I found a lot of logspam from cyclopscore; will post tomorrow there.

**Comment by 7eggert** [comment]
With the new world created for https://github.com/CyclopsMC/CyclopsCore/issues/148
Only your mods are installed:
ColossalChests-1.16.4-1.7.12.jar
CommonCapabilities-1.16.4-2.5.5.jar
CyclopsCore-1.16.4-1.9.5.jar
IntegratedCrafting-1.16.4-1.0.11.jar
IntegratedDynamics-1.16.4-1.2.0.jar
IntegratedREST-1.16.4-1.1.2.jar
IntegratedTerminals-1.16.4-1.1.1.jar
IntegratedTunnels-1.16.4-1.6.15.jar

An uncollossal chest takes 1 second to open, a 2³ collossal chest takes 12 seconds.

**Comment by 7eggert** [comment]
Update: I installed the current version of CyclopsCore and CollossalChest and the other updates from your mod; now the DISABLED animation starts immediately and the chest opens.

CyclopsCore-1.16.4-1.11.0.jar
ColossalChests-1.16.4-1.7.13.jar
