### ISSUE TITLE
disabled animation happens

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/ColossalChests#147]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Animation of chest happens even though it's disabled

#### Steps to reproduce the problem:

set in
colossalchests-common.toml

chestAnimation = false

#### Expected behaviour:

No animation
____

#### Versions:
ColossalChests-1.16.4-1.7.13.jar
CyclopsCore-1.16.4-1.11.0.jar
forge-1.16.4-35.1.37-installer.jar
- Minecraft: 1.16.4

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Disabling animation seems to work just fine for me.
It's possible that you have to restart your game after changing the configs.
