### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/ColossalChests#148]
#### Issue type:

- :bug: Bug 

____

#### Short description:

`README.md` has a broken link;
https://github.com/CyclopsMC/ColossalChests/blame/master-1.16/README.md#L10
```markdown
For when regular chests are too small

All stable releases (including deobfuscated builds) can be found on [CurseForge](http://minecraft.curseforge.com/mc-mods/colossal-chests/files).

[Development builds](https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/colossalchests/ColossalChests/) are hosted by [JFrog Artifactory](https://www.jfrog.com/artifactory/).
```

#### Steps to reproduce the problem:

1. Go to the repo page
2. Press on the CurseForge link
3. Get sent to an old/broken CurseForge page

#### Expected behaviour:

Link directs to `https://www.curseforge.com/minecraft/mc-mods/colossal-chests/files`.
I haven't checked, but this is probably a problem on the other repos too (I'm not sure how long ago curseforge changed the url format).

____

#### Versions:

- This mod: All (link added in 2424ebe55968ed1dd1ff0c899882be740d5edc5d)
- Minecraft: N/A
- Forge: N/A

#### Log file:
N/A

**Comment by rubensworks** [comment]
Thanks for reporting!
