### ISSUE TITLE
Uncolossal chest does not drop when broken

### ISSUE THREAD

**Issue by jstansel** [CyclopsMC/ColossalChests#153]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Breaking the uncolossal chest in survival its so slow, with axe is a little bit faster, but still doesn't drop the chest when it breaks

#### Steps to reproduce the problem:

1. Place an uncollosal chest
2. Break it using a stone axe

#### Expected behaviour:

I expected it to break at the same speed as a vanilla chest and to drop itself when broken.
____

#### Versions:

- This mod: 1.18.1-1.8.2
- Minecraft: 1.18.1
- Forge: 39.0.79

**Comment by rubensworks** [comment]
Thanks for reporting!
