### ISSUE TITLE
Colossal Chests doesn't work in ATM7 1.18.2

### ISSUE THREAD

**Issue by RubberDuckky** [CyclopsMC/ColossalChests#154]
#### Issue type:

- :bug: Bug 

____

#### Short description: 

Basically when you try to load the game with these 2 mods in the mods folder, the game crashes shortly after being launched. Which brings up an error for being unable to reload tempad shaders.

#### Steps to reproduce the problem:

1. Place Colossal chests and Cyclops core mods into the mods folder

#### Expected behaviour:

Well, I expected to be able to slap these into the mods folder and have it run just fine without crashing.
____

#### Versions:

- This mod: ColossalChests-1.18.1-1.8.3 and CyclopsCore-1.18.1-1.13.4
- Minecraft: 1.18.2
- Forge: 40.0.54

#### Log file:

https://pastebin.com/kgJ2vNy1

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
1.18.2 is not supported yet (but it is being worked on).
