### ISSUE TITLE
The bigger the chest, the more lag it creates

### ISSUE THREAD

**Issue by Test-Account666** [CyclopsMC/ColossalChests#158]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

I create a colossal chest, and as soon as I open it, I'm lagging, the bigger, the more lag it creates.

This lag also seems to affect the server, if you have a mod like Tom's Storage Network or AE2 connected to the chest. 

#### Steps to reproduce the problem:

Try open a colossal chest and try connecting it to a network like AE2 or Tom's

____

#### Versions:

- This mod: 1.8.4
- Minecraft: 1.19.2 
- Forge: 43.2.6

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share a profiling log as explained in https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md#performance-issues-snail ?

<blockquote><img src="https://opengraph.githubassets.com/f9dcb526b4638d723c97a0bef73e1076a698c89afd95d9679205530c1e1f0f20/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</div></blockquote>

**Comment by Test-Account666** [comment]
Oh, missed that part, sorry 😅

Will do that as soon as possible
