### ISSUE TITLE
bigger chests should have different chest opening sound

### ISSUE THREAD

**Issue by mbalc** [CyclopsMC/ColossalChests#159]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

wasn't there a feature in earlier versions, where the sound of opening a huge chest would get stretched and modulated to sound lower, the bigger the chest was? it was a really cool thing, it gave you a sense of progression when upgrading to a bigger chest, and I really miss that on my 1.19 modpack

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Ah, that's not working anymore?
Sounds like a bug then.

**Comment by mbalc** [comment]
umm, at least in 1.19.2 it does not
