### ISSUE TITLE
port to Architectury API

### ISSUE THREAD

**Issue by MimzyFang** [CyclopsMC/ColossalChests#161]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
Architectury API is an API to make multiplatform mods if the mod would be ported to it, it would be compatible with Fabric/Quilt, Forge and NeoForge 

This is essentially useful since NeoForge dropped Forge mod support in 1.20.4 effectively splitting the forge community and making it really hard to make Modpacks in future versions of the game

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
I don't have multiloader plans at this time, but this may change in the future. Will update to 1.20.4 NeoForge though.
