### ISSUE TITLE
A small difference in the description part of curseforge page and in the receipt

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/ColossalChests#162]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

Here receipt produces 2 wall blocks:
https://media.forgecdn.net/attachments/28/524/schermafbeelding-2015-11-11-om-16.png
but only 1 in the game

#### Expected behaviour:

____

#### Versions:

- This mod: ColossalChests-1.20.1-1.8.4.jar 
- Minecraft: 1.20.1
- Forge: 1.47.100

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Fixed now on Curseforge and Modrinth.
