### ISSUE TITLE
Iron Golem spawns inside the chest 5x5x5

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/ColossalChests#163]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Iron Golem spawns inside the chest 5x5x5

#### Expected behaviour:

____

#### Versions:

- This mod: ColossalChests-1.20.1-1.8.4.jar 
- Minecraft: 1.20.1
- Forge: forge-1.20.1-47.1.100-installer.jar

**Comment by rubensworks** [comment]
Thanks for reporting!
