### ISSUE TITLE
Chests are full on creation of chest

### ISSUE THREAD

**Issue by GmanAtheist** [CyclopsMC/ColossalChests#164]
#### Issue type: When adding the core block and opening the chest, it is full of items from Minecraft. 

- :bug: Bug 

____

#### Steps to reproduce the problem: 25021960jgnmmaking a 3x3 chest. Chest render fine but since yesterday , every time I build a chest it is full completely with random items from MC.

1. ...

#### Expected behaviour: Chest to be empty

____

#### Versions:

- This mod: ColossalChests-1.19.2-1.9.0
- Minecraft: Java
- Forge: 43.3.13

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm guessing you set `creativeChests` to `true` in your config file. Setting it to `false` should fix the problem.

**Comment by GmanAtheist** [comment]
> I'm guessing you set `creativeChests` to `true` in your config file. Setting it to `false` should fix the problem.

AH!. My bad. I did just that. Thanks a lot for your help . rubensworks
