### ISSUE TITLE
Big troubles with update 1.20.1-1.8.5

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/ColossalChests#165]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The update ColossalChests-1.20.1-1.8.4.jar to ColossalChests-1.20.1-1.8.5.jar creates many random errors

#### Steps to reproduce the problem:

Sorry, but there are no crushes, so no crush dumps. The simplest way for me to reproduce is try to create a new world, but bug is random, so may be it's only on my list of mods. The issue is definitely in collosallchests mod, because if downgrade back, problems disappear.

Possible glitches:
Game stops responding on exit (Alt+F4)
Game stops responding on world loading
Game stops responding on world creation
Some hot keys/commands (binded to magic casts) stops work or ignored (nothing happen)

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Hmm, since I don't have time to fix this problem this week, I'll just pull the releases from CF and MR.
