### ISSUE TITLE
Lose a world after crash, after add interface to colossal chest

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/ColossalChests#169]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Impossible to load a world after add ID interface to colossal chest.

#### Steps to reproduce the problem:

This crash is occurred after
1. Create a colossal chest 5x5, core on upper corner.
2. Attach item interface from Integrated Dynamics from above
 -- First strange thing: item interface looks like interface + already attached cable
3. Try attach a real cable to item interface with click to wall 1 m above the item interface upper side, not to the interface itself
4. Crash
5. Reload MC - Crash

#### Versions:

- This mod: colossalchests-1.21.1-neoforge-1.8.7-121.jar 
- Minecraft: 1.21.1
- Mod loader version: neoforge 21.1.68
- Also 
IntegratedDynamics-1.21.1-neoforge-1.23.9.jar 
IntegratedTerminals-1.21.1-neoforge-1.5.2.jar 
IntegratedCrafting-1.21.1-neoforge-1.1.10.jar 
IntegratedTunnels-1.21.1-neoforge-1.8.28.jar 

#### Log file:

[crash-2024-10-16_15.28.55-server.txt](https://github.com/user-attachments/files/17395036/crash-2024-10-16_15.28.55-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by uhloin** [comment]
Reproduced in creative mode with 2x2x2 chest and without other mods. Interface is appear with cable and glitches are started. Can break cable (by hand in creative), but cannot break interface, can set interface above other interface and if try set cable above the interface - crush,

**Comment by rubensworks** [comment]
This was caused due to the recent multiloader update.
Is fixed in the newest release.

**Comment by uhloin** [comment]
Yes, thank you, it works fine
