### ISSUE TITLE
Crash with Every Compat installed

### ISSUE THREAD

**Issue by ToxinZangoose** [CyclopsMC/ColossalChests#172]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When loading Colossal Chests and Every Compat together on 1.21.1 (neoforge), the game crashes repeatedly on my modpack.

#### Steps to reproduce the problem:

1. Use my mod list, including Colossal Chests, its dependencies, and Every Compat and its dependencies.
2. Launch game
3. Crash

#### Expected behaviour:

I expected no conflict between Every Compat and Colossal Chests.
Note: This only happened with my modpack, not when I tested the mods by themselves.
____

#### Versions:

- This mod: Colossal Chests 1.8.8
- Minecraft: 1.21.1
- Mod loader version: 21.1.73 (NeoForge)

#### Log file:

https://mclo.gs/HCGImrw

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I don't see Colossal Chests being mentioned in the crashlog.
The crash seems to be caused by `xxrexraptorxx.additionalstructures.utils.Events.onClientTick`.
I recommend reporting to this mod's issue tracker first, and optionally link back to this issue.
Happy to make changes on my end if needed.
