### ISSUE TITLE
Upgrading from Forge to NeoForge, from 1.20.1 to 1.21.1, reduce the stored stacks to 1 item.

### ISSUE THREAD

**Issue by fabianofa** [CyclopsMC/ColossalChests#173]
#### Issue type:

- :question: Question 

____

#### Question:
Hi dev, I'd like to check if I'm taking a step too long here with the upgrades.

I have a server currently running on Forge: 47.2.0, and a client on: 1.20.1. 
We wanted some new feature from the 1.21.1 then I decided to try to upgrade both things at once, from Forge to NeoForge, from 1.20.1 to 1.21.1.

All booted fine, but once I opened Colossal Chests and/or IronChests entities, all the item stacks that were stored into them were reduced to a single item.

In your experience, would it perhaps give us a better result going from Forge to Forge, between 1.20.1 to 1.21.1 first, then from Forge to NeoForge? 

The alternative for us would be of course storing items in vanilla chests, those didn't lose the stacks for whatever reason. But that's quite a painful process and I'd like to check with you first if that's known and if there is an alternative for it.

Thanks in advance.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
The Forge->Forge update first _may_ go better, but I'm not sure tbh.
When porting across MC versions, I don't keep things backwards-compatible, just like most (all?) other mods.
I'm surprised this update worked out for you, even just partially.

In theory, custom logic could be added to enable this transition in a backwards-compatible manner. But this would require changes to the code.
