### ISSUE TITLE
1.21.1 Farbic Game crashes when a creeper Explodes

### ISSUE THREAD

**Issue by JackMidnightVR** [CyclopsMC/ColossalChests#174]
#### Issue type:Crashing

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Have a big chest
2. let a creeper explode
3.before it explodes game closes

#### Expected behaviour:

creeper explodes normaly
____

#### Versions:

- This mod: 1.21.1-1.8.8
- Minecraft: 1.21.1
- Mod loader version: Fabric 0.16.7

#### Log file: https://mclo.gs/7sumKfr#L5

[crash-2024-11-12_04.14.48-server.txt](https://github.com/user-attachments/files/17710760/crash-2024-11-12_04.14.48-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
