### ISSUE TITLE
Chest direction limited

### ISSUE THREAD

**Issue by JonaBrackenwood** [CyclopsMC/ColossalChests#20]
The direction the chest faces is limited on which side the controller is placed.
When a controller is placed in a corner it can only face two directions: west or east.

So if you make a 2 by 2 chest, this one is limited to east or west.

Chest direction should be based on where the player stood when the last block to make a valid colossal chest multiblock structure is placed..

**Comment by rubensworks** [comment]
I thought I fixed this limitation to east and west already...
(Chest direction will only be based on the location of the core, not the facing of the player, but that shouldn't be a problem.)
