### ISSUE TITLE
Visual glitches when extra core or wall is present

### ISSUE THREAD

**Issue by JonaBrackenwood** [CyclopsMC/ColossalChests#22]
Observe this situation:
![image](https://cloud.githubusercontent.com/assets/1567798/12703246/ccae9f4c-c83e-11e5-837f-44e547e27387.png)

When a block of the valid colossal chest is broken, this results in weird visual glitches..
Only one block in left upper corner broken (this was the core):
![image](https://cloud.githubusercontent.com/assets/1567798/12703249/ecd225fa-c83e-11e5-806a-6e8910e73d1f.png)

Only one block in left bottom corner broken (this was a wall):
![image](https://cloud.githubusercontent.com/assets/1567798/12703256/11317892-c83f-11e5-8c24-29307e40aa2d.png)
This still is a valid multiblock somehow, but the bottom left block isn't there.
When this block is placed black, you get a wall rendered in a colossal chest:
![image](https://cloud.githubusercontent.com/assets/1567798/12703270/4b9b7618-c83f-11e5-8940-c557457967a2.png)

If you break multiple blocks it gets even weirder. You can sustain a valid colossal chest with one core and 3 walls this way.

**Comment by rubensworks** [comment]
Probably related to #21. I think I'll just make it impossible to place other chest blocks next to an existing chest, like for the vanilla chests, otherwise things will become quite complex.

(I like the detailed bug report :+1: )
