### ISSUE TITLE
Crash when braking mini chest

### ISSUE THREAD

**Issue by zedner** [CyclopsMC/ColossalChests#23]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.5.jar)
  LoadingPlugin (FastLeaveDecay-1.2.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7.2.16. 04.41
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at org.cyclops.cyclopscore.helper.BlockHelpers.getSafeBlockStateProperty(BlockHelpers.java:34)
    at org.cyclops.colossalchests.tileentity.TileUncolossalChest.getRotation(TileUncolossalChest.java:178)
    at org.cyclops.cyclopscore.client.render.tileentity.RenderTileEntityModel.renderTileEntityAt(RenderTileEntityModel.java:51)
    at org.cyclops.cyclopscore.client.render.tileentity.RenderTileEntityModel.func_180535_a(RenderTileEntityModel.java:103)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:897)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1697)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1307)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at org.cyclops.cyclopscore.helper.BlockHelpers.getSafeBlockStateProperty(BlockHelpers.java:34)
    at org.cyclops.colossalchests.tileentity.TileUncolossalChest.getRotation(TileUncolossalChest.java:178)
    at org.cyclops.cyclopscore.client.render.tileentity.RenderTileEntityModel.renderTileEntityAt(RenderTileEntityModel.java:51)
    at org.cyclops.cyclopscore.client.render.tileentity.RenderTileEntityModel.func_180535_a(RenderTileEntityModel.java:103)

-- Block Entity Details --
Details:
    Name: uncolossalChest // org.cyclops.colossalchests.tileentity.TileUncolossalChest
    Block type: ID #963 (tile.blocks.colossalchests.uncolossalChest // org.cyclops.colossalchests.block.UncolossalChest)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (-174,86,214), Chunk: (at 2,5,6 in -11,13; contains blocks -176,0,208 to -161,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:897)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1697)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1522)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Zednerr'/168, l='MpServer', x=-171.41, y=86.00, z=213.37]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -236.00,64.00,212.00 - World: (-236,64,212), Chunk: (at 4,4,4 in -15,13; contains blocks -240,0,208 to -225,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 316145 game time, 1 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 59 total; [EntityBat['Bat'/22033, l='MpServer', x=-132.51, y=18.75, z=257.50], EntityBat['Bat'/24471, l='MpServer', x=-233.52, y=26.51, z=236.50], EntityBat['Bat'/17183, l='MpServer', x=-147.28, y=44.58, z=144.27], EntityPig['Pig'/32, l='MpServer', x=-240.06, y=87.00, z=233.03], EntityChicken['Chicken'/39, l='MpServer', x=-220.28, y=77.00, z=162.66], EntityChicken['Chicken'/40, l='MpServer', x=-220.66, y=76.00, z=273.34], EntityPlayerSP['Zednerr'/168, l='MpServer', x=-171.41, y=86.00, z=213.37], EntityBat['Bat'/45, l='MpServer', x=-202.53, y=13.10, z=137.75], EntityPig['Pig'/46, l='MpServer', x=-193.81, y=93.00, z=241.31], EntityItem['item.item.dyePowder.black'/54, l='MpServer', x=-182.88, y=42.00, z=216.75], EntityItem['item.item.dyePowder.black'/57, l='MpServer', x=-181.84, y=53.00, z=219.34], EntityChicken['Chicken'/59, l='MpServer', x=-186.50, y=87.00, z=286.31], EntityItem['item.item.egg'/958, l='MpServer', x=-124.06, y=86.00, z=257.94], EntityItem['item.item.dyePowder.black'/69, l='MpServer', x=-169.50, y=37.00, z=236.19], EntityItem['item.item.dyePowder.black'/70, l='MpServer', x=-169.50, y=37.00, z=235.41], EntityChicken['Chicken'/72, l='MpServer', x=-152.38, y=71.00, z=169.44], EntityChicken['Chicken'/73, l='MpServer', x=-148.50, y=93.00, z=231.44], EntityChicken['Chicken'/74, l='MpServer', x=-146.69, y=105.00, z=268.53], EntityChicken['Chicken'/75, l='MpServer', x=-144.63, y=106.00, z=276.34], EntityItem['item.item.egg'/76, l='MpServer', x=-147.25, y=105.00, z=268.22], EntityItem['item.item.egg'/77, l='MpServer', x=-150.41, y=101.00, z=264.72], EntityBat['Bat'/18509, l='MpServer', x=-176.75, y=36.10, z=153.50], EntitySquid['Squid'/26961, l='MpServer', x=-181.19, y=43.00, z=219.63], EntityChicken['Chicken'/82, l='MpServer', x=-138.44, y=71.00, z=170.13], EntityChicken['Chicken'/83, l='MpServer', x=-139.38, y=78.00, z=185.56], EntityItem['item.item.egg'/84, l='MpServer', x=-139.44, y=78.00, z=185.06], EntityPig['Pig'/85, l='MpServer', x=-133.00, y=80.00, z=198.13], EntityChicken['Chicken'/86, l='MpServer', x=-137.38, y=82.00, z=214.38], EntityCow['Cow'/87, l='MpServer', x=-139.50, y=87.00, z=234.69], EntityPig['Pig'/88, l='MpServer', x=-146.72, y=94.00, z=235.47], EntityCow['Cow'/89, l='MpServer', x=-134.41, y=86.00, z=245.72], EntityChicken['Chicken'/90, l='MpServer', x=-129.41, y=87.00, z=250.63], EntityChicken['Chicken'/91, l='MpServer', x=-131.38, y=87.00, z=251.59], EntityRabbit['Rabbit'/92, l='MpServer', x=-130.25, y=88.00, z=255.88], EntityItem['item.item.egg'/93, l='MpServer', x=-128.63, y=87.00, z=250.31], EntityBat['Bat'/94, l='MpServer', x=-152.25, y=41.10, z=275.25], EntityBat['Bat'/25698, l='MpServer', x=-165.69, y=54.88, z=251.75], EntityChicken['Chicken'/99, l='MpServer', x=-124.66, y=75.00, z=175.50], EntityItem['item.item.dyePowder.black'/8804, l='MpServer', x=-175.13, y=40.00, z=222.88], EntityChicken['Chicken'/101, l='MpServer', x=-126.38, y=77.71, z=198.50], EntityItem['item.item.egg'/102, l='MpServer', x=-126.81, y=77.00, z=199.63], EntityRabbit['Rabbit'/103, l='MpServer', x=-118.13, y=85.00, z=214.34], EntityRabbit['Rabbit'/104, l='MpServer', x=-125.94, y=86.00, z=246.22], EntityCow['Cow'/105, l='MpServer', x=-126.34, y=83.00, z=239.31], EntityBat['Bat'/13417, l='MpServer', x=-93.28, y=42.38, z=220.56], EntityChicken['Chicken'/106, l='MpServer', x=-126.38, y=83.00, z=237.56], EntityItem['item.item.egg'/107, l='MpServer', x=-126.47, y=83.00, z=237.94], EntityRabbit['Rabbit'/108, l='MpServer', x=-119.50, y=87.00, z=248.16], EntityChicken['Chicken'/109, l='MpServer', x=-126.56, y=83.00, z=240.31], EntityRabbit['Rabbit'/110, l='MpServer', x=-118.75, y=88.00, z=253.94], EntityItem['item.item.egg'/111, l='MpServer', x=-127.06, y=83.00, z=240.72], EntityChicken['Chicken'/112, l='MpServer', x=-123.38, y=86.00, z=257.50], EntityRabbit['Rabbit'/113, l='MpServer', x=-123.31, y=87.00, z=261.69], EntityBat['Bat'/22258, l='MpServer', x=-162.97, y=40.34, z=270.47], EntityCow['Cow'/121, l='MpServer', x=-109.31, y=86.00, z=217.59], EntityItem['item.item.dyePowder.black'/8825, l='MpServer', x=-179.91, y=42.00, z=217.47], EntityChicken['Chicken'/122, l='MpServer', x=-110.34, y=87.00, z=240.59], EntityRabbit['Rabbit'/124, l='MpServer', x=-110.78, y=88.00, z=280.94], EntityChicken['Chicken'/125, l='MpServer', x=-103.53, y=91.00, z=282.66]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics 
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 442387928 bytes (421 MB) / 947564544 bytes (903 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.19 Powered by Forge 11.15.1.1732 Optifine OptiFine_1.8.9_HD_U_H2 35 mods loaded, 35 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1732.jar) 
    UCHIJAAAA   Forge{11.15.1.1732} [Minecraft Forge](forge-1.8.9-11.15.1.1732.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1777-universal.jar) 
    UCHIJAAAA   ChestTransporter{2.2.0} [Chest Transporter](ChestTransporter-2.2.0-MC1.8.9.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.10} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.10.jar) 
    UCHIJAAAA   cyclopscore{0.5.0} [Cyclops Core](CyclopsCore-1.8.9-0.5.0.jar) 
    UCHIJAAAA   colossalchests{1.3.0} [Colossal Chests](ColossalChests-1.8.9-1.3.0.jar) 
    UCHIJAAAA   craftingcraft{2.0.6} [CraftingCraft](craftingcraft-mc1.8.9-2.0.6.jar) 
    UCHIJAAAA   CustomBackgrounds{1.0} [Custom Backgrounds](CustomBackgrounds-1.0.jar) 
    UCHIJAAAA   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-1.2.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.6.jar) 
    UCHIJAAAA   furnus{1.6} [Furnus](Furnus-1.8.9-1.6.jar) 
    UCHIJAAAA   Harvest{1.8.9-1.0.0-2} [Harvest](Harvest-1.8.9-1.0.0-2.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks](InventoryTweaks-1.60-beta-30.jar) 
    UCHIJAAAA   ironbackpacks{1.8-1.0.7} [Iron Backpacks](IronBackpacks-1.8-1.0.7.jar) 
    UCHIJAAAA   IronChest{6.0.123.769} [Iron Chest](ironchest-1.8.9-6.0.123.769.jar) 
    UCHIJAAAA   JEI{2.24.5.128} [Just Enough Items](jei_1.8.9-2.24.5.128.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.1.5} [Thaumcraft](Thaumcraft-1.8.9-5.1.5.jar) 
    UCHIJAAAA   JEIAddons{0.9.0.34} [Just Enough Items Addons](JEIAddons_1.8.9-0.9.0.34.jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.32} [LunatriusCore](LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
    UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJAAAA   MouseTweaks{2.6.0} [Mouse Tweaks](MouseTweaks-2.6.0-mc1.8.9.jar) 
    UCHIJAAAA   MultiPageChest{1.4.0} [Multi Page Chest](MultiPageChest-1.4.0-MC1.8.9.jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.1-2.jar) 
    UCHIJAAAA   notenoughwands{1.2.4} [Not Enough Wands](notenoughwands-1.8.9-1.2.4.jar) 
    UCHIJAAAA   parachutemod{1.2.2} [Parachute Mod](parachutemod-ng-1.8.9-1.2.2-324.jar) 
    UCHIJAAAA   portablecrafting{1.8.9-1.1} [Portable Crafting](PortableCrafting-1.8.9-1.1.jar) 
    UCHIJAAAA   quickstart{1.0} [Quickstart](quickstart-1.1.jar) 
    UCHIJAAAA   RecipeTooltips{1.0.14} [RecipeTooltips](RecipeTooltips-1.8.9-1.0.14.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste](redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   SimilsaxTranstructors{1.8.8.16} [Similsax Transtructors](SimilsaxTranstructors-1.8.8.16.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAAAA   uncraftingtable{1.0.2} [Uncrafting Grinder](UncraftingGrinder-1.8.9-1.0.2.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.5.jar)

LoadingPlugin (FastLeaveDecay-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon HD 7660D + HD 7700 Dual Graphics'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
Launched Version: 1.8.9-forge1.8.9-11.15.1.1732
LWJGL: 2.9.4
OpenGL: AMD Radeon HD 7660D + HD 7700 Dual Graphics GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Unity-Complete-1.2.0.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD A10-5800K APU with Radeon(tm) HD Graphics 
```

**Comment by zedner** [comment]
i put down this uncolossal chest in creative and broke it with left click, then it crashed, also when braking colossal chest wall in survival its so slow, with axe is a little bit faster but still dont drop anything after i brake it

**Comment by rubensworks** [comment]
Lower required tool material in a55484556d4bd56ee0e737fa20ee2590f1cccb36
Expect a new bugfix release soon.

**Comment by jstansel** [comment]
> when braking colossal chest wall in survival its so slow, with axe is a little bit faster but still dont drop anything after i brake it

This is happening for me with the uncolossal chest in 1.18.1
Version: 1.18.1-1.8.2
Forge: 39.0.79

**Comment by rubensworks** [comment]
@jstansel Could you open a new issue for this?
