### ISSUE TITLE
Minor versioning bug with 1.9-1.3.4

### ISSUE THREAD

**Issue by matt81093** [CyclopsMC/ColossalChests#27]
When loading ColossalChests-1.9-1.3.4, it lets me know there is a new version "1.3.3". Just wanted to pass that on.

**Comment by rubensworks** [comment]
Ah, apparently I forgot to update its version in the version repo, thanks for letting me know!
Fixed in CyclopsMC/Versions@eb59df5c31dd7cf9a8ae265f0606e54b6deed1e4

**Comment by matt81093** [comment]
Glad to assist
