### ISSUE TITLE
Replacing a chest wall with an interface deletes the item contents of the colossal chest

### ISSUE THREAD

**Issue by patrickclank9** [CyclopsMC/ColossalChests#30]
Also, breaking an interface on a colossal chest spills out all the items. I'm assuming that should only happen when breaking the chest core.

**Comment by rubensworks** [comment]
You're correct, that's not supposed to happen.
Thanks for reporting this.

**Comment by rubensworks** [comment]
Ok, this was a though one to fix...
Will push a new release between here and a week.
