### ISSUE TITLE
Crash when closing colossal chest

### ISSUE THREAD

**Issue by megaloloful** [CyclopsMC/ColossalChests#31]
Sometimes when I close a colossal chest (or uncolossal chest) the game crashes. 

Forge 12.18.0.1996
CyclopsCore 1.9.4-0.9.3
Colossal chests  1.9.4-1.3.5

Crashlog: http://pastebin.com/gStFvHUn

**Comment by rubensworks** [comment]
@immortaleeb I assume you fixed this in CyclopsCore a while back, is this correct?

**Comment by immortaleeb** [comment]
@rubensworks I have only made the sound changes to evilcraft.
The changes haven't been merged to CyclopsCore's master branch either: https://github.com/CyclopsMC/CyclopsCore/tree/sound-changes

**Comment by rubensworks** [comment]
Ok, this will be resolved in the next bugfix update.
