### ISSUE TITLE
Make Chests Searchable?

### ISSUE THREAD

**Issue by ManMan36** [CyclopsMC/ColossalChests#39]
When chests get truly colossal, and one has utilized the capabilities to their fullest potential, it can be hard to find what one wants in the chests. Having a search bar would be nice.

**Comment by rubensworks** [comment]
It would be nice, I agree :) But that would take away the simplicity of the (cheap & early-game) chests, which is why I don't want to add it.
If you want such a search functionality, you can use storage enchancement mods like Refined Storage or Ender IO, they work together with this mod.
