### ISSUE TITLE
colossal chest nbt size problem

### ISSUE THREAD

**Issue by charchess** [CyclopsMC/ColossalChests#40]
Hi, 

am running a server 1.10.2 - forge 12.18.1.2071 with lots of mods and I came accross a problem with colossal chest twice

I had a 4x4x4 chest, full, tried to expand it to 5 and it came with some nbt size problem limit. I did accept the situation and started a new server.

I came across another similar problem but client side, chest being heavily loaded (5x5x5) it said  io.netty.handler.timeout.readtimeoutexception:java.lang.runtimeexception: tried to read NBT tag that was too big;tried to allocate: 2097158 bytes where max allowed: 2097152.

removed colossa chest and was able to log on ...

for your information, I came across a problem today involving botania/storage drawer soooo ... maybe it's botania who has an issue... just feel I'd let you know and maybe double checking the nbt memory usage when the chest is heavily loaded ?

feel free to ask if you need something (or close this ticket if you don't think CC may have a problem)

oh ...and keep up the good work, this mod really is nice

Charchess

**Comment by rubensworks** [comment]
I anticipated that this might happen. That is why I added the `maxSlotsPerPacket` option in the config file. Try decreasing this value, and see if this your problem. Let me know which value worked for you, and I'll use that as default value for the next update.

**Comment by charchess** [comment]
sadly I am not sure I still have the backup of the server in that state, will double check and let you know/do some tries

**Comment by charchess** [comment]
sorry, don't have the backup anymore and moved to mc 1.7.10 due to lag on server and some non compatible mods I wanted to add.
If I ever come accross the same problem on another server, I'll keep you in touch

**Comment by rubensworks** [comment]
Note to self: decrease default maxSlotsPerPacket

**Comment by p455w0rd** [comment]
this is still happening, we've lowered the config option to 1500 and rasied to 3500..we've tried everything..it's happening on a silver chest which has 9k+ slots..I'm assuming you're storing all of this in a single TE..a better idea that would significantly decrease NBT size would be to create custom slots which allow for more then 64 item per slot..I do this with the /dank/null

**Comment by rubensworks** [comment]
I've been thinking about this, and I could do something about this by not using a fixed, but a dynamic fragmentation of NBT. Will probably require some hacking around some Vanilla code though...

**Comment by Morpheus1101** [comment]
Im now myself getting this error although slightly different with a 6x6 Colossal Diamond Chest thats not even 1/4 full..Im now stuck and unable to join world and have the chest actively loaded without getting error again.

Log @ https://puu.sh/tC1of/0ed730b777.log

**Comment by rubensworks** [comment]
@Morpheus1101 Is it a regression? i.e. does it only occur since the new version of the mod?

If it didn't occur before, could you try the following dev builds to see in which version it _does_ work for you again?
* [build 138](https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.4.2-138/ColossalChests-1.10.2-1.4.2-138.jar) 57021f373303fc818e1e9e6302c6d0858b934c09
* [build 139](https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.4.2-139/ColossalChests-1.10.2-1.4.2-139.jar) c0b51ba63bf81325e64880e2eefc223af7de8566
* [build 138](https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.4.2-140/ColossalChests-1.10.2-1.4.2-140.jar) adafcccedc1f2034c7bc648c4412ef0068f95f28

**Comment by Morpheus1101** [comment]
Im downgrading verion by version untill i can successfully re-join an remain joined and i'll post which version it is.

**Comment by Morpheus1101** [comment]
All release vers on Curse are no good, now trying the dev builds you have listed

**Comment by rubensworks** [comment]
@Morpheus1101 Ok, interesting, so you're encountering a special case that has never worked before.
I suspect an ItemStack that has a very large NBT tag somewhere in the chest, is that possible?

(No need to test the other dev builds btw, if the releases don't work, the later dev builds won't work either)

**Comment by Morpheus1101** [comment]
tbh i couldnt tell you, since ive prev not encounted this prior to today, im not even sure how to find out

**Comment by rubensworks** [comment]
There are some things I could try, but that won't be before Sunday unfortunately.

Note to self: Double-check to make sure chunk load packet for TE's doesn't send inventory data to clients.

**Comment by Morpheus1101** [comment]
Thats ok, this new MMD-Dev pack isnt going live for a few weeks yet, its just intial testing to work out easy found crashes an bugs :)

**Comment by Morpheus1101** [comment]
Actually i suspect this isnt actually your mod thats causing it, well not directly anyway, i believe it maybe HoloInventory thats causing the problem, which im about to test, as i suspect that mod dosent have support etc for the size of colossal chests and when going to display the items contained in the chest, is when the NBT error occurs..

**Comment by Morpheus1101** [comment]
ok unf with that mod disabled it didnt solve it and i was really sure it would lol

**Comment by rubensworks** [comment]
@Morpheus1101 It could be that another mod may be causing this as well. Perhaps you could try disabling other mods as well, as far as that's possible.

**Comment by Morpheus1101** [comment]
Ok, so after further discussion with another another modder we've discovered the issue to be caused by a mod called Cyclic which seems to trigger a bug in IC2 ... so thankfully this wasnt an issue with Colossal Chest :D

**Comment by rubensworks** [comment]
@Morpheus1101 Ok, one of those obscure cross-mod issues then. Good to know, and thanks for letting me know :)

**Comment by dougwebb** [comment]
I've run into what appears to be the same problem, or closely related. See [FTB Forum](https://forum.feed-the-beast.com/threads/game-crash-when-pointing-at-colossal-chest-interface-block.214960/) for some reports. Looking at the interface block on a chest has started crashing the app, and the logs mention NBT size limit being exceeded. It looks like maxSlotsPerPacket was replaced with maxPacketBufferSize; I tried setting that to 10000 and still crashed. 

In my case I've got a 7x7x7 wood chest a little over 50% full, and the single interface block as a Refined Storage storage interface attached to it. This is in the Sky Factory 3 mod pack. My setup had been working fine until I upgraded Sky Factory to 3.0.6. I don't know if there are any usual items in my chest; they're pretty much the same items I had before the upgrade. Later tonight I'll probably look into removing things to see if that helps, but trying to identify a particular item that's a problem isn't going to be feasible, with so many items in storage.

**Comment by rubensworks** [comment]
@dougwebb If it only crashes when looking at the interface block, it sounds like an issue with a mod like WAILA that sends the complete inventory to the client, which shouldn't happen. I suggest you identify that mod and report it to their issue tracker.

**Comment by powder** [comment]
Can successfully still reproduce the crash.  In this particular case, I've been able to solve it by turning off WAILA (numpad 1).

**Comment by rubensworks** [comment]
@powder Have a look at #65

**Comment by Morpheus1101** [comment]
Are you using WAILA or HWYLA?  The reason i mention this is WAILA by prof mobius is outdated an hasnt been updated in a while and HWYLA has taken its place and carried the mod on an being regularly updated
