### ISSUE TITLE
Bug: Colossal Chests

### ISSUE THREAD

**Issue by p455w0rd** [CyclopsMC/ColossalChests#44]
# Forwarded from MinecraftModDevelopment/MMD-Dev-Server#147 by @MrTaco9001 : 

Right clicking on a colassal chest makes all the items in my inventory go away. They don't get deleted but they only way to get them back is updating my inventory.

**Comment by rubensworks** [comment]
This has been fixed in 9132afaee650bc1f6ee20560e9532b208705de3a, and is included in the new release.
I'll post an issue to request an update.
