### ISSUE TITLE
Chest not working

### ISSUE THREAD

**Issue by BrofistKittycat** [CyclopsMC/ColossalChests#45]
I was having an odd problem on the 1.9.4 version: creating the multiblock would work, but unfortunately I couldn't open the chest. It would play the opening sound, show the chest opening, but no GUI. Also, it would make my items disappear until I relogged. I was using Cyclops Core v. 0.8.0 and Colossal Chests v. 1.3.6. Great mod, amazing concept, and an unfortunate bug. I would **love** to use this mod, so please fix it!

**Comment by BrofistKittycat** [comment]
If it helps, I was also using the following mods:
CodeChickenCore-1.9.4-2.0.4.71-universal
DynamicLights-1.9.4
EnderBags-1.9.4-2.0.0
Fast**Leave**Decay-MC1.9.4-1.2.1
Furnus-1.9.4-1.83
NotEnoughItems-1.9.4-2.0.1.133-universal
OptiFine_1.9.4_HD_U_B6
planttech-1.6.0 - 1.9.4
ReapMod 1.1.1

**Comment by rubensworks** [comment]
Please update to the latest version (1.4.0), you're using a months old version that was buggy.
