### ISSUE TITLE
If a chest is to big, it crashes the game

### ISSUE THREAD

**Issue by funniray** [CyclopsMC/ColossalChests#53]
I tried to make a 128x128x128 chest, while I was placing the blocks, my game ended up crashing.

Crash log: https://gist.github.com/funniray/fe85b18f609a03ef1842dc5ddef7730f

Edit: by the way, I'm playing skyfactory 3.0.1

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@5f653d8fc2dc5b44dfc66b11a3366f0d03212f43
New release coming soon.
