### ISSUE TITLE
[1.10.2] Colossal Chest items become invisible

### ISSUE THREAD

**Issue by Morpheus1101** [CyclopsMC/ColossalChests#54]
When 1st opening the chest all contents are visible np's at all, but after a very short period of time all thew contents become invisible until you click on one of them to pick up an they all re-appear.  I believe it occurs when coronets are updating.

Can be re-produced consistently.  Setup in pic below

![2017-01-05_09 56 38](https://cloud.githubusercontent.com/assets/10524952/21663664/5d0c088c-d32d-11e6-8322-da761dc538fa.png)

**Comment by rubensworks** [comment]
What do you mean exactly with "the new contents"?

Are those the slots that are being filled by the EIO pipe? Were these items already visible before?

When picking up one item and all of them becoming visible? Do those item become invisible after a while again?

What do you mean with "coronets"?

**Comment by Morpheus1101** [comment]
When you 1st open the colossal chest all contents are visible with no issues.  However after a very short period they dissapear from view, i don tknow if its when a series of new items have been transfered into the chest via the EnderIO conduits, but thats what occurs.

When they've become invisible, the moment you pick 1 item up from the colossal chest, they all become visible.  Howeevr if you leave it invisible, sometimes a few slots i.e. 3-4 become visible.

coronets is a typo lol, im presuming it was meant to be contents

**Comment by Morpheus1101** [comment]
This video gives a quick demonstration of what happens.  https://puu.sh/tbSyT/07de15470a.flv

**Comment by rubensworks** [comment]
@Morpheus1101 That's very useful, thanks!

**Comment by Morpheus1101** [comment]
Any update on this?

**Comment by rubensworks** [comment]
@Morpheus1101 Unfortunately not no, #58 currently has a higher priority, so I want to resolve that one before looking into this one.

Perhaps @Runesmacher could have a look if he has time?...

**Comment by Runesmacher** [comment]
I don't seem to be able to replicate the issue in my DEV enviroment,
Local world or even a local dedicated server.
Does it happen on a remote server?

@Morpheus1101 could you give me the version you are using? Does it still happen with the latest release?
If yes => please provide me with a mod list

**Comment by Morpheus1101** [comment]
Yes this is a remote server: *core vers 0.9.0 & CC v1.4.2

Mods List @ https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/453

**Comment by rubensworks** [comment]
Related: c0b51ba63bf81325e64880e2eefc223af7de8566

Note to self: this issue is probably related to the server sending an chunk/tile update packet to the client, which for Colossal Chests always contains an empty inventory. A solution would be to catch these packets and ignore the inventory tag, so that the client-side inventory is not overwritten with an empty one.

**Comment by Morpheus1101** [comment]
This would actually make sense with your explanation, i look fwd to testing out the fixed vers

**Comment by rubensworks** [comment]
The last commit will probably resolve this issue.

@Morpheus1101 Last dev build if you're interested in testing it: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/colossalchests/ColossalChests/1.10.2-1.4.2-140/ColossalChests-1.10.2-1.4.2-140.jar

**Comment by Morpheus1101** [comment]
Testing confirms this is indeed fixed

**Comment by rubensworks** [comment]
That's great news! This fix will be included in a release that will hopefully be pushed later this week.
