### ISSUE TITLE
[Enhancement] Different wood chests

### ISSUE THREAD

**Issue by Voxel-Friend** [CyclopsMC/ColossalChests#56]
Just as there is ironchest-like variants, there could be spruce, acacia etc. If quark is installed, could use it's textures.

**Comment by rubensworks** [comment]
I feel like this is out-of-scope for this mod, so I won't implement this.
It should be possible however for other mods to add this behaviour to this mod, such as quark.

**Comment by Voxel-Friend** [comment]
Fair enough.
