### ISSUE TITLE
chest size/items can hold

### ISSUE THREAD

**Issue by frogalo** [CyclopsMC/ColossalChests#57]
I would like to know how many items I can hold with different sizes of chests

**Comment by rubensworks** [comment]
> (diameter ^ 3) * 27 for the wooden chest. So a 3x3x3 chest will give 729 slots, while an 11x11x11 will give 35 937 slots. The multipliers for the metal variants can be found here: https://github.com/CyclopsMC/ColossalChests/blob/master-1.10/src/main/java/org/cyclops/colossalchests/block/PropertyMaterial.java#L82-L87
