### ISSUE TITLE
BUG with building chest with builders wand

### ISSUE THREAD

**Issue by frogalo** [CyclopsMC/ColossalChests#59]
So I play SkyFactory 3 and I was making a 16x16x16 iron chest (it can hold 14M items). I was going to use builders wand but when I click it on the chest walls it instead of iron walls it is putting copper. I didn't make any copper walls and have none in my inventory.

**Comment by rubensworks** [comment]
Sounds like a bug with the builders wand, better to report on their issue tracker.
