### ISSUE TITLE
Request High Priority - Quark Support 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/ColossalChests#60]
Please Read This for Details!
https://github.com/Vazkii/Quark/issues/292

**Comment by rubensworks** [comment]
I prefer not to implement any third-party interfaces on tiles and items. Capabilities, however, would be something I'd be willing to add.

**Comment by P3rf3ctXZer0** [comment]
@rubensworks It seems to already be in your mod. That is why I closed the issue.
