### ISSUE TITLE
Add way to rotate Chests when core is placed in top/bottom center

### ISSUE THREAD

**Issue by Runesmacher** [CyclopsMC/ColossalChests#61]
When placing a chestcore in the center of the top or bottom layer, the chest faces the default location, a feature to rotate the chest after the fact would be a nice addition

**Comment by rubensworks** [comment]
This would require significant changes to the multiblock algorithm, so I won't implement this.
I also don't see the need for it, since changing the position of the core allows you to choose the rotation. Together with the interface blocks, you should be able to do anything you want.
