### ISSUE TITLE
suggestion and question

### ISSUE THREAD

**Issue by mightydanp** [CyclopsMC/ColossalChests#63]
1. what does Maximum buffer byte size for adaptive inventory slots fragmentation mean. does it mean the max number of slots.
2. if not then can you add a config where you can set the max number of slots if you only want a 2by2 or make it where you can change  where you can set the amount of slots lower some how xD 216 is kinda to big to me.

**Comment by rubensworks** [comment]
1. It literally means the maximum number of bytes to send over a packet. So if a slot contains an item with a large NBT tag, this will reduce the number of items that fit in one packet more than an item with no NBT tag.
2. So you are complaining about the number of slots in the chest being too large? Maybe Colossal Chests is not the mod for you then... 😛
