### ISSUE TITLE
NBT tag too big - Causing client disconnect.

### ISSUE THREAD

**Issue by Rob5Underscores-zz** [CyclopsMC/ColossalChests#65]
A client crash with the following error: 
http://pastebin.com/8q5hJQks

Occurs when looking at a (specific) diamond chest core. I figure an item inside the chest must cause it? Issue remains even when part of the chest is broken.

Colossal Chests: 1.5.0
Forge: 2202
CommonCapabilities: 1.3.0

**Comment by rubensworks** [comment]
Sounds like an issue with Waila or something related, can you reproduce it with just Colossal Chests and CyclopsCore installed?

**Comment by Rob5Underscores-zz** [comment]
That's what I thought.

I removed WAWLA (it wasn't installed serverside) and the issue persisted.

I can't test it easily with just those mods since its on a production server.

**Comment by rubensworks** [comment]
Not much I can do with this information then. Colossal Chests does nothing when looking at a core, so another mod must be causing this.

**Comment by Rob5Underscores-zz** [comment]
Yes. Apologies.

Forgot to remove HWYLA. Issues most likely lies there.

**Comment by Rob5Underscores-zz** [comment]
https://github.com/TehNut/HWYLA/issues/42

**Comment by rubensworks** [comment]
@Rob5Underscores Thanks! I don't think their current fix will resolve the issue though, they shouldn't send all NBT data from the chest to the client at all, but we'll see.
