### ISSUE TITLE
Crash when targeting interface block.  

### ISSUE THREAD

**Issue by lob-star** [CyclopsMC/ColossalChests#66]
I'm not sure on the specifics, but I have a reproducible error that puts players into a fatal error loop after targeting the interface black on a 9x9 chest.  It affects players immediately after login as their character will still be facing the block upon login.  FTB Sky Factory 3 ver. 3.0.6.  I'm happy to provide a world save or do testing if needed.

**Comment by rubensworks** [comment]
Duplicate of #65, not caused by Colossal Chests.
