### ISSUE TITLE
can't link

### ISSUE THREAD

**Issue by wompel** [CyclopsMC/ColossalChests#72]
i don't know why or how but i'm playing on the foolcraft modpack but i can't seem to link my pick to the chest. tried a 5x5x5 and a 6x6x6 plz help

**Comment by rubensworks** [comment]
I have no idea what you are talking about. 'Linking' chests is not a feature of this mod. You'll probably want to report this to your modpack author.

**Comment by wompel** [comment]
i mean linking tools 2 the chest as seen in a vid of iskall85 foolcraft episode 1 near the end

**Comment by legodude17** [comment]
You have to shift right click on the chest core.
