### ISSUE TITLE
Texture overlay offset bug

### ISSUE THREAD

**Issue by tatoyoda600** [CyclopsMC/ColossalChests#74]
On Sky Factory 3 (1.10.2) I created a 3x3x3 chest and for some reason the bottom texture looked weird.
![colossalchestsbug](https://cloud.githubusercontent.com/assets/26845479/24583234/0c7c7b96-171a-11e7-81e4-41ced188afd5.png)

**Comment by rubensworks** [comment]
A small texture offset mistake apparently.

**Comment by tatoyoda600** [comment]
Is there any way to fix this?
Because it happens with every size of chest and so if I make a 16x16 chest there is going to be a giant square underneath which isn't something I want to happen.

**Comment by rubensworks** [comment]
Of course I can fix this, I won't have time for it anytime soon though.
