### ISSUE TITLE
[1.11.2] Broken textures with Iron Chests

### ISSUE THREAD

**Issue by TheLimePixel** [CyclopsMC/ColossalChests#75]
On the latest 1.11.2 version of the mod it seems that there's a problem with the Iron Chests mod integration and it displays a missing texture. It's quite surprising how long it took for this to be found.
![2017-04-09_20 49 14](https://cloud.githubusercontent.com/assets/25333164/24840085/f427d8bc-1d66-11e7-99ba-62638c9de4b3.png)

**Comment by rubensworks** [comment]
In the meantime you can disable iron chest textures from the CC config file.
