### ISSUE TITLE
1.10.2 full chest causes mob lag

### ISSUE THREAD

**Issue by Mrjalmari** [CyclopsMC/ColossalChests#76]
5x5x5 iron chest full of cobblestone, trying to pipe in more with pipes like in ender IO conduits, causes mob lag. I also tested this with other pipes and storages

**Comment by rubensworks** [comment]
What is "mob lag"? Do you mean a low TPS?

What piping systems exactly? This is probably related to #58.

**Comment by Mrjalmari** [comment]
https://youtu.be/zPFQ14MQNdU

**Comment by rubensworks** [comment]
Not something that can be solved on our end, reported to Ender IO: SleepyTrousers/EnderIO#4178
