### ISSUE TITLE
CTD (Crash to desktop) when sort button pressed (Inventory Tweaks mod with Colossal Chest mod v1.5.1

### ISSUE THREAD

**Issue by KusanagiRyu** [CyclopsMC/ColossalChests#80]
Hi Ruben, 
As mentioned above and in #68 , CTD occured with 1.5.1 (current latest). here's a pastebin link to it; [HERE](https://pastebin.com/kH1SvRnV).

**Comment by rubensworks** [comment]
Duplicate of #77
