### ISSUE TITLE
Please document the size of the chests

### ISSUE THREAD

**Issue by 7eggert** [CyclopsMC/ColossalChests#81]
For chest users, one of the most important functions is the size of the chests they build. I had to dig through the code to see the size of the chest - counting would be harder. Please update either the curseforge page or create a small wiki page (or allow me to do that) do document the chest sizes.

The formula is:
- Number_of_item_Slots = number of rows * 9
- Number_of_Rows = Math.ceil((Math.pow(getSizeSingular(), 3) * 27) * getMaterial().getInventoryMultiplier() / 9);
- = Math.ceil(Math.pow(getSizeSingular(), 3) * 3 * Material_Factor)

(Does the vector you access using getSizeSingular() provide a cubic zize? Not important though.)

Material_Factor:
- Wood: 1
- Copper: 1.666
- Iron: 2
- Silver: 2.666
- Gold: 3
- Diamond: 4
- Obsidian: 4

**Comment by rubensworks** [comment]
You're right, I should've added this to the curseforge description a long time ago.

Done! :-)
