### ISSUE TITLE
Cannot upgrade a 16x16x16 chest from wood to iron.

### ISSUE THREAD

**Issue by JadeDrgn** [CyclopsMC/ColossalChests#84]
Everytime I try to upgrade it, it just eats the core and then tells me i'm missing items. Not sure if I'm supposed to progressively upgrade it or not but either way this is buggy as it deletes the core from my inventory everytime I get a new one and try again.

Console output when I try to upgrade with everything in my inventory: https://pastebin.com/VDtFsppB

**Comment by rubensworks** [comment]
Looks like something I missed during the 1.11 port.

**Comment by rubensworks** [comment]
You don't need to progressively upgrade. The issue was caused by the core vanishing.
