### ISSUE TITLE
Moving items on scroll

### ISSUE THREAD

**Issue by BenjaminCo** [CyclopsMC/ColossalChests#86]
I've noticed that scrolling on items put them out/in of the chest. Cuz of the many slots i scroll down or up and it's doing mess in my inventories. It's maybe a native minecraft feature but it would be great to have a button on colossal chest ui to disable/enable this feature.

**Comment by rubensworks** [comment]
As far as I know this is a feature of inventory tweaks, so you might be able to disable it there.
