### ISSUE TITLE
[1.12] Not being able to craft any chest Interface from Colossal Chests.

### ISSUE THREAD

**Issue by Boomflex** [CyclopsMC/ColossalChests#87]
https://github.com/AllTheMods/ATM-3/issues/11

CC version: 1.12-1.6.2
forge version: 14.21.1.2396

As said in the title, unable to craft any chest interface.

![image](https://user-images.githubusercontent.com/22868795/27987683-79598aba-6409-11e7-92e7-9f525624dba7.png)

**Comment by rubensworks** [comment]
Fixed in CyclopsCore 0.10.8
