### ISSUE TITLE
[1.12] Broken textures with Iron Chests

### ISSUE THREAD

**Issue by TheLimePixel** [CyclopsMC/ColossalChests#89]
Well the same problem was on the 1.11.2 version a month ago and now it's on the 1.12 version. Simply, with iron chests installed, all chests besides the wooden one have a broken texture.

 Also, if you have a crafting table next to a colossal chest and look at it from the right angle, the rendering slightly messes up: 
 https://cdn.discordapp.com/attachments/334673790028087299/335060350816878592/efba2af41cd6352a59efbb1cef8a0afd.png

**Comment by rubensworks** [comment]
It looks like IC changed the location of their textures *again*, will have to update the link.

Regarding the latter, than seems to be a vanilla issue, as we just call the vanilla chest renderer.
