### ISSUE TITLE
Crash when placing Colossal Chest Blocks

### ISSUE THREAD

**Issue by gefailter** [CyclopsMC/ColossalChests#92]
CC version: 1.12-1.6.5
Forge version: 2485
Server: true

When trying to place any wooden colossal chest block, a player crashes and gets this crash log: http://paste.feed-the-beast.com/view/c077f498

If anything else is needed, I'll try to provide it.

**Comment by rubensworks** [comment]
It crashes on it not finding a method, while that method in fact does exist.
So there must be some other mod messing with it.

Can you try reproducing this without any other mods installed? (Except for CyclopsCore of course).

**Comment by gefailter** [comment]
Happens in SP as well with only CC as the installed mod, I tried placing an un-colossal chest and got this; http://paste.feed-the-beast.com/view/1b98f578

**Comment by rubensworks** [comment]
I'll try it myself soon, but my guess is that something might be going wrong on your end.

**Comment by gefailter** [comment]
Thank you, good sir, well that'd mean there's something wrong with 2 players since the first crash was someone from the server.
