### ISSUE TITLE
[1.12.1] Crash when placing via the Builder from RFTools

### ISSUE THREAD

**Issue by Boomflex** [CyclopsMC/ColossalChests#93]
Colossal Chests v1.6.5
Cyclops Core v0.10.15
Forge v14.22.0.2464

Crash when placing Colossal Chest blocks with the Builder from RFTools.

https://pastebin.com/TjXHLueA

**Comment by rubensworks** [comment]
Duplicate of #92, this was fixed in release 1.6.6.
