### ISSUE TITLE
Visual Glitch

### ISSUE THREAD

**Issue by ZephaniahNoah** [CyclopsMC/ColossalChests#94]
MC: 1.12.2
ColossalChests: 1.6.7
![chest](https://s26.postimg.org/4p2sccr53/2017-09-29_15.58.57.png)
Rarely happens.

**Comment by rubensworks** [comment]
This is caused by another mod (I don't know which one) that is not correctly using the OpenGL environment in its TESR.
This issue can also occur on vanilla chests.

I suggest removing blocks in the area until it is fixed, that block's mod will be the cause of it.

**Comment by ZephaniahNoah** [comment]
That is a colossal vanilla chest. I'm using a resourcepack. It happens when they're in a certain position on the screen and I look at a specific angle. Most of the time it looks fine.
