### ISSUE TITLE
Items disappearing from Colossal chest

### ISSUE THREAD

**Issue by JSchober93** [CyclopsMC/ColossalChests#95]
For reference I play SMP with the Foolcraft 2 pack through MultiMC and I have had different sized colossal chests with this happening. I never use the core as a pseudo-chest for moving, I've always piped items using ender-io pipes if I want to move or upgrade(of which this is not the issue). 

I currently am using a storage bus with the AE2 network linked to a 7x7 chest and I have had several items deleting themselves. They have not turned invisible. All of my AE2 storage cards are Precise Partitioned so only the items I want should be going to those. I don't know how to force a duplication but it happens somewhat often, through random happenings. 

AE2: RV4-stable-1
Colossal: 1.10.2-1.6.0

**Comment by rubensworks** [comment]
This looks related to a Forge issue (MinecraftForge/MinecraftForge#4413). Unfortunately, they won't backport the potential fix for this to 1.10. So your best bet is to update to 1.12 if you want to avoid these rare issues.

I leave this open for now, in case anyone can provide a way to consistently reproduce this. Preferably with just Vanilla+CC.

**Comment by rubensworks** [comment]
Forge considers this fixed, if anyone would encounter this problem with Forge 1.12.2, please comment here.

**Comment by Furious1964** [comment]
Still happening in 1.12.2.

**Comment by rubensworks** [comment]
@Furious1964 Any more information you can give me?

**Comment by Furious1964** [comment]
Bug Report

I put items into the chest via an Ender pouch/chest and the items show up but when I finished adding more, I lost 70% of everything I had.
Steps to Reproduce (for bugs)

    Added items.
    Added more items and look into the AE2 System.
    Logged of and then on again and I lost stuff again.
    Replaced AE2 System with RFTools Storage Scanned and same thing.

Logs

    Client/Server Log:
    Crash Log:

Client Information

    Minecraft Version: 1.12.2
    Forge Version: 14.23.5.2775
    Modpack Version: Stoneblock Mod Pack 1.0.28
    Server/LAN/Single Player: Single Player
    Optifine Installed: Yes, HD U E2
    Shaders Enabled: No

Added an RFTools Storage Scanner to the chest in place of the AE2 System and it does the same thing. When I place items into the chest via those systems, when I log off and on again the items are deleted.

I made both a 9x9 and a 20x20 wooden chest and in both instances, items are deleted upon logging into the game.

[latest.log](https://github.com/CyclopsMC/ColossalChests/files/2591710/latest.log)

**Comment by Furious1964** [comment]
> 
> 
> @Furious1964 Any more information you can give me?

Updated info.

**Comment by rubensworks** [comment]
Ok, thanks for the info, this sounds like #116 then.

**Comment by Furious1964** [comment]
It's not quite the same as I didn't break any side of the chest.
